import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { supabase } from "./supabase";
import "./style.css";

const categories=["ID Card","Electronics","Books","Wallet / Money","Keys","Accessories","Bags","Clothing","Other"];
const statusLabel={lost:"Lost",found:"Found",returned:"Returned",archived:"Archived"};

function App(){
  const [session,setSession]=useState(null),[profile,setProfile]=useState(null);
  const [view,setView]=useState("home"),[items,setItems]=useState([]),[claims,setClaims]=useState([]),[ownerClaims,setOwnerClaims]=useState([]),[notifications,setNotifications]=useState([]);
  const [authMode,setAuthMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState("");
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[category,setCategory]=useState("all"),[loading,setLoading]=useState(false);

  const refresh=async(s=session)=>{if(!s)return; await Promise.all([loadItems(),loadClaims(s),loadOwnerClaims(s),loadNotifications(s)]);};
  async function loadItems(){
    const {data,error}=await supabase.from("items_public").select("*").order("created_at",{ascending:false});
    if(error){setError(error.message);return}
    const rows=data||[];
    const {data:ownedRows}=session?await supabase.from("items").select("id").eq("owner_id",session.user.id):{data:[]};
    const ownedIds=new Set((ownedRows||[]).map(x=>x.id));
    const withImages=await Promise.all(rows.map(async x=>{
      if(!x.image_path)return x;
      const {data:urlData}=supabase.storage.from("lost-found-images").getPublicUrl(x.image_path);
      return {...x,is_owner:ownedIds.has(x.id),image_url:urlData?.publicUrl||null};
    }));
    setItems(withImages);
  }
  async function loadProfile(s){const {data}=await supabase.from("profiles").select("id,full_name,role").eq("id",s.user.id).single();setProfile(data||null);}
  async function loadClaims(s){const {data,error}=await supabase.from("claims").select("id,item_id,claimant_id,status,message,created_at,items:items(title,status,owner_id),profiles:profiles!claims_claimant_id_fkey(full_name)").eq("claimant_id",s.user.id).order("created_at",{ascending:false});if(!error)setClaims(data||[]);}
  async function loadOwnerClaims(s){const {data:owned}=await supabase.from("items").select("id,title,status").eq("owner_id",s.user.id);const ids=(owned||[]).map(x=>x.id);if(!ids.length){setOwnerClaims([]);return}const {data,error}=await supabase.from("claims").select("id,item_id,claimant_id,status,message,created_at,profiles:profiles!claims_claimant_id_fkey(full_name),items:items(title,status)").in("item_id",ids).order("created_at",{ascending:false});if(!error)setOwnerClaims(data||[]);}
  async function loadNotifications(s){const {data}=await supabase.from("notifications").select("*").eq("user_id",s.user.id).is("read_at",null).order("created_at",{ascending:false}).limit(10);setNotifications(data||[]);}
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)loadProfile(data.session)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s){loadProfile(s)}else setProfile(null)});return()=>subscription.unsubscribe()},[]);
  useEffect(()=>{if(session)refresh(session)},[session]);
  async function auth(e){e.preventDefault();setError("");setNotice("");setLoading(true);if(authMode==="signup"){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)setError(error.message);else setNotice("Account created. Check your college email if confirmation is enabled.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}setLoading(false)}
  async function logout(){await supabase.auth.signOut();setView("home")}
  async function markNotificationsRead(){if(!notifications.length)return;await supabase.from("notifications").update({read_at:new Date().toISOString()}).in("id",notifications.map(n=>n.id));setNotifications([])}
  const visible=useMemo(()=>items.filter(x=>(filter==="all"||x.status===filter)&&(category==="all"||x.category===category)&&`${x.title} ${x.category} ${x.location} ${x.description}`.toLowerCase().includes(search.toLowerCase())),[items,filter,category,search]);
  if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} submit={auth} error={error} notice={notice} loading={loading}/>;
  const isAdmin=profile?.role==="admin";
  return <div className="app">
    <header><button className="brand brandBtn" onClick={()=>setView("home")}>🔎 <span>Campus Lost & Found</span></button>
      <nav><button className={view==="home"?"active":""} onClick={()=>setView("home")}>Dashboard</button><button className={view==="report"?"active":""} onClick={()=>setView("report")}>Report</button><button className={view==="items"?"active":""} onClick={()=>setView("items")}>Browse</button><button className={view==="claims"?"active":""} onClick={()=>setView("claims")}>My Claims</button><button className={view==="reports"?"active":""} onClick={()=>setView("reports")}>My Reports</button>{isAdmin&&<button className={view==="admin"?"active":""} onClick={()=>setView("admin")}>Admin</button>}</nav>
      <div className="user"><span>{profile?.full_name||session.user.email}</span>{notifications.length>0&&<button className="bell" title="Notifications" onClick={()=>{setView("notifications");markNotificationsRead()}}>🔔<i>{notifications.length}</i></button>}<button onClick={logout}>Logout</button></div>
    </header>
    <main>
      {view==="home"&&<Home items={items} setView={setView}/>} 
      {view==="report"&&<Report session={session} setView={setView} notify={setNotice} refresh={refresh}/>} 
      {view==="items"&&<Browse items={visible} allItems={items} session={session} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} category={category} setCategory={setCategory} notify={setNotice} refresh={refresh}/>} 
      {view==="claims"&&<Claims claims={claims}/>}
      {view==="reports"&&<OwnerReports claims={ownerClaims} session={session} notify={setNotice} refresh={refresh}/>}
      {view==="notifications"&&<Notifications session={session}/>} 
      {view==="admin"&&isAdmin&&<Admin items={items} session={session} notify={setNotice} refresh={refresh}/>} 
      {notice&&<div className="toast" onClick={()=>setNotice("")}>{notice}</div>}
      {error&&<div className="toast errorToast" onClick={()=>setError("")}>{error}</div>}
    </main>
  </div>
}

function Auth(p){return <div className="auth"><div className="authbox"><div className="brand big">🔎 Campus Lost & Found</div><div className="eyebrow">CAMPUS COMMUNITY</div><h1>{p.mode==="login"?"Welcome back":"Create your account"}</h1><p>Securely reconnect lost belongings without exposing personal contact details.</p><form onSubmit={p.submit}>{p.mode==="signup"&&<input placeholder="Full name" required value={p.name} onChange={e=>p.setName(e.target.value)}/>}<input type="email" placeholder="College email" required value={p.email} onChange={e=>p.setEmail(e.target.value)}/><input type="password" placeholder="Password" required minLength="6" value={p.password} onChange={e=>p.setPassword(e.target.value)}/><button className="primary" disabled={p.loading}>{p.loading?"Please wait…":p.mode==="login"?"Sign in":"Create account"}</button></form>{p.error&&<div className="error">{p.error}</div>}{p.notice&&<div className="notice">{p.notice}</div>}<button className="link" onClick={()=>p.setMode(p.mode==="login"?"signup":"login")}>{p.mode==="login"?"New student? Create account":"Already registered? Sign in"}</button><div className="securityNote">🔒 No public phone numbers · Private claims · Campus-safe handover</div></div></div>}

function Home({items,setView}){const lost=items.filter(x=>x.status==="lost").length,found=items.filter(x=>x.status==="found").length,returned=items.filter(x=>x.status==="returned").length;return <><section className="hero"><div><small>CAMPUS COMMUNITY</small><h1>Find it.<br/><span>Report it. Return it.</span></h1><p>A privacy-first platform for reconnecting students with lost belongings.</p><div className="heroActions"><button className="primary" onClick={()=>setView("report")}>＋ Report an Item</button><button className="ghost" onClick={()=>setView("items")}>Browse Reports →</button></div></div><div className="heroVisual"><div className="floatingCard">🔐<b>Privacy first</b><span>Contact details stay hidden</span></div><div className="bag">🎒</div></div></section><div className="stats"><b>{lost}<small>Active lost reports</small></b><b>{found}<small>Found reports</small></b><b>{returned}<small>Returned</small></b></div><div className="sectionTitle"><div><small>RECENT ACTIVITY</small><h2>Latest reports</h2></div><button className="link" onClick={()=>setView("items")}>View all →</button></div><div className="grid">{items.slice(0,3).map(x=><Item key={x.id} x={x}/>)}</div>{!items.length&&<div className="empty"><div>📦</div><h3>No reports yet</h3><p>Be the first person to report a lost or found item.</p><button className="primary" onClick={()=>setView("report")}>Create first report</button></div>}</>}

function Report({session,setView,notify,refresh}){const [type,setType]=useState("lost"),[title,setTitle]=useState(""),[cat,setCat]=useState(categories[0]),[loc,setLoc]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[desc,setDesc]=useState(""),[image,setImage]=useState(null),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();if(!image){notify("Please upload an item photo before submitting.");return}if(!["image/png","image/jpeg","image/webp"].includes(image.type)){notify("Only PNG, JPG or WEBP images are allowed.");return}if(image.size>5*1024*1024){notify("Image must be 5 MB or smaller.");return}setBusy(true);let image_path=null;const ext=image.name.split(".").pop().toLowerCase();const path=`${session.user.id}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from("lost-found-images").upload(path,image,{upsert:false,contentType:image.type});if(up.error){notify("Image upload failed: "+up.error.message);setBusy(false);return}image_path=path;const {error}=await supabase.from("items").insert({owner_id:session.user.id,title,category:cat,type,location:loc,event_date:date,description,image_path});if(error){await supabase.storage.from("lost-found-images").remove([image_path]);notify(error.message)}else{notify("Report submitted securely ✓");await refresh(session);setView("items")}setBusy(false)}
 return <><div className="head"><small>CREATE REPORT</small><h1>Report an item</h1><p>Share enough detail to identify the item, but never publish your phone number or email.</p></div><form className="form" onSubmit={submit}><div className="switch"><button type="button" className={type==="lost"?"on":""} onClick={()=>setType("lost")}>🔴 Lost</button><button type="button" className={type==="found"?"on":""} onClick={()=>setType("found")}>🟢 Found</button></div><label>Item name<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Black wallet"/></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Campus location<input required value={loc} onChange={e=>setLoc(e.target.value)} placeholder="e.g. Library, Block A"/></label><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Description<textarea required value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Useful identifying details. Avoid private contact information."/></label><label>Item photo <span className="requiredMark">* Required</span><input type="file" required accept="image/png,image/jpeg,image/webp" onChange={e=>setImage(e.target.files?.[0]||null)}/>{image&&<small className="fileMeta">Selected: {image.name} · {(image.size/1024/1024).toFixed(2)} MB</small>}</label><div className="formHint">📸 A clear item photo is required for every report. PNG, JPG or WEBP · maximum 5 MB.<br/>🔒 Contact information is never shown on public reports.</div><button className="primary" disabled={busy}>{busy?"Submitting…":"Submit Securely"}</button></form></>}

function Browse({items,allItems,session,search,setSearch,filter,setFilter,category,setCategory,notify,refresh}){return <><div className="head"><small>SEARCH & DISCOVER</small><h1>Lost & Found</h1><p>Browse reports while keeping reporter identity private.</p></div><div className="toolbar"><input placeholder="🔎 Search item, category or location…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All status</option><option value="lost">Lost</option><option value="found">Found</option><option value="returned">Returned</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="resultsBar"><span>{items.length} report{items.length!==1?"s":""}</span><span>🔒 Private contact system</span></div><div className="grid">{items.map(x=><Item key={x.id} x={x} session={session} notify={notify} refresh={refresh} allItems={allItems}/>)}</div>{!items.length&&<div className="empty"><div>🔎</div><h3>No matching reports</h3><p>Try a different search or filter.</p></div>}</>}

function Item({x,session,notify,refresh}){const [open,setOpen]=useState(false),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);const isOwner=Boolean(x.is_owner);async function claim(){if(!session)return;setBusy(true);const {error}=await supabase.from("claims").insert({item_id:x.id,claimant_id:session.user.id,message:msg});if(error)notify(error.message);else{notify("Private claim submitted ✓");setOpen(false);setMsg("");await refresh?.(session)}setBusy(false)}return <article className="card itemCard">{x.image_url&&<img className="itemImage" src={x.image_url} alt=""/>}<div className="row"><span className="icon">{x.category==="ID Card"?"🪪":x.category==="Books"?"📚":x.category==="Keys"?"🔑":x.category==="Electronics"?"📱":x.category==="Bags"?"🎒":"📦"}</span><span className={"badge "+x.status}>{statusLabel[x.status]||x.status}</span></div><h3>{x.title}</h3><p>📍 {x.location} · {x.event_date}</p><p>{x.description}</p><div className="privacy">🔒 Reporter identity & contact hidden</div>{x.status!=="returned"&&!isOwner&&<button className="secondary" onClick={()=>setOpen(!open)}>💬 {open?"Close":"Request Item"}</button>}{isOwner&&<div className="ownerHint">✓ Your report</div>}{open&&<div className="claim"><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Explain why you think this item is yours…"/><button className="primary" disabled={busy||msg.trim().length<5} onClick={claim}>{busy?"Sending…":"Send Private Claim"}</button></div>}</article>}

function Claims({claims}){return <><div className="head"><small>PRIVATE</small><h1>My Claims</h1><p>Track requests you have submitted.</p></div><div className="grid">{claims.length?claims.map(c=><article className="card claimCard" key={c.id}><div className="row"><b>Claim #{c.id.slice(0,8)}</b><span className={"badge "+c.status}>{c.status}</span></div><h3>{c.items?.title||"Item"}</h3><p>{c.message}</p><small className="muted">Submitted {new Date(c.created_at).toLocaleString()}</small>{c.status==="accepted"&&<div className="successBox">✓ Claim accepted. Arrange handover through your campus-approved process.</div>}{c.status==="rejected"&&<div className="warningBox">This claim was not accepted. You can browse other reports.</div>}</article>):<div className="empty"><div>💬</div><h3>No claims yet</h3><p>When you find an item that may be yours, send a private claim.</p></div>}</div></>}

function OwnerReports({claims,session,notify,refresh}){const [busy,setBusy]=useState("");async function decide(c,decision){setBusy(c.id);const {error}=await supabase.rpc(decision==="accepted"?"accept_claim":"reject_claim",{p_claim_id:c.id});if(error)notify(error.message);else{notify(decision==="accepted"?"Claim accepted — item marked returned ✓":"Claim rejected ✓");await refresh(session)}setBusy("")}return <><div className="head"><small>MY REPORTS</small><h1>Incoming claims</h1><p>Review private requests for items you reported. Your contact details remain hidden.</p></div><div className="adminList">{claims.length?claims.map(c=><article className="adminClaim" key={c.id}><div><div className="row"><b>{c.items?.title||"Your reported item"}</b><span className={"badge "+c.status}>{c.status}</span></div><p><strong>Claim from:</strong> {c.profiles?.full_name||"Student"}</p><p>{c.message}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>{c.status==="pending"&&<div className="adminActions"><button className="accept" disabled={busy===c.id} onClick={()=>decide(c,"accepted")}>✓ Accept & Return</button><button className="reject" disabled={busy===c.id} onClick={()=>decide(c,"rejected")}>Reject</button></div>}</article>):<div className="empty"><div>📬</div><h3>No incoming claims</h3><p>When another student claims one of your reports, it will appear here.</p></div>}</div></>}

function Notifications({session}){const [list,setList]=useState([]);useEffect(()=>{supabase.from("notifications").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(30).then(({data})=>setList(data||[]))},[session]);return <><div className="head"><small>UPDATES</small><h1>Notifications</h1><p>Claim decisions and important activity.</p></div><div className="notificationList">{list.length?list.map(n=><article className="notification" key={n.id}><div>🔔</div><div><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.created_at).toLocaleString()}</small></div></article>):<div className="empty">No notifications.</div>}</div></>}

function Admin({items,session,notify,refresh}){const [claims,setClaims]=useState([]),[busy,setBusy]=useState("");async function load(){const {data,error}=await supabase.from("claims").select("id,item_id,claimant_id,status,message,created_at,items:items(title,owner_id,status),profiles:profiles!claims_claimant_id_fkey(full_name)").order("created_at",{ascending:false});if(error)notify(error.message);else setClaims(data||[])}useEffect(()=>{load()},[]);const pending=claims.filter(c=>c.status==="pending");async function decide(c,decision){setBusy(c.id);const {error}=await supabase.rpc(decision==="accepted"?"accept_claim":"reject_claim",{p_claim_id:c.id});if(error)notify(error.message);else{notify(`Claim ${decision} ✓`);await load();await refresh(session)}setBusy("")}return <><div className="head"><small>ADMIN CONTROL CENTER</small><h1>Moderation dashboard</h1><p>Review claims and protect the campus handover process.</p></div><div className="adminStats"><div><b>{items.length}</b><span>Total reports</span></div><div><b>{items.filter(x=>x.status==="lost").length}</b><span>Lost</span></div><div><b>{items.filter(x=>x.status==="found").length}</b><span>Found</span></div><div><b>{pending.length}</b><span>Pending claims</span></div></div><div className="sectionTitle"><div><small>CLAIM REVIEW</small><h2>Incoming requests</h2></div></div><div className="adminList">{claims.length?claims.map(c=><article className="adminClaim" key={c.id}><div><div className="row"><b>{c.items?.title||"Item"}</b><span className={"badge "+c.status}>{c.status}</span></div><p><strong>Claimant:</strong> {c.profiles?.full_name||"Student"}</p><p>{c.message}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>{c.status==="pending"&&<div className="adminActions"><button className="accept" disabled={busy===c.id} onClick={()=>decide(c,"accepted")}>✓ Accept</button><button className="reject" disabled={busy===c.id} onClick={()=>decide(c,"rejected")}>Reject</button></div>}</article>):<div className="empty">No claims to review.</div>}</div></>}

createRoot(document.getElementById("root")).render(<App/>);
